language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  # - psql -c 'create database palettepicker;' -U postgres
  - psql -c 'CREATE DATABASE project_test;' -U postgres
  - npm run migrate
  - npm run seed
